### ISSUE TITLE
[GKE issues] CAdvisor unresponsive

### ISSUE THREAD

**Issue by akshhack** [saidsef/grafana-loki-on-k8s#49]
Hey Said, 

I got around some of the issues by hacking the YAML with not the greatest level of understanding of each parameter. I'm now still facing issues with the grafana-cm.yaml not being apt for GKE -- wherein CAdvisor is unresponsive thereby disallowing me from accessing CPU / mem metrics in the cluster. 

It'll be great if I can set up a short call with yourself to get this up and running -- will be a huge help for me and hopefully anybody else who uses this in the future. Thank you so much. 

Here is my calendly if it makes things easier -- https://www.calendly.com/akshatp-cs/chat

**Comment by saidsef** [comment]
Hiya @akshhack,

GKE will prevent you running privileged containers in AutoPilot unless you are a Google Partner.  Interestingly, I used to use google/cadvisor for monitoring containers resource usage and performance specs of running containers. [This is not allowed in GKE AutoPilot](https://forum.checkmk.com/t/kubernetes-cluster-collector-not-getting-the-cpu-memory-percentage-usage-metrics/39338/13) .

If you must use GKE AutoPilot I strongly suggest you use/enable the build-in monitoring or use Google Partner tools from the market place.

GKE AutoPilot has limitations and deliberate constraints, if you want to use your own tools you might want to reconsider.
