### ISSUE TITLE
Unable to parse config: /etc/promtail/kubernetes-config.yaml

### ISSUE THREAD

**Issue by bestyuantao** [saidsef/grafana-loki-on-k8s#52]
Hi Said，

got below issue, seems /etc/promtail/kubernetes-config.yaml doesn't existed, do you have this file in local? or do you have any suggestions, thanks
![image](https://github.com/saidsef/grafana-loki-on-k8s/assets/40762870/2f7bce94-e86f-497f-9e35-79ddd42c8159)

**Comment by saidsef** [comment]
Hi @bestyuantao, thanks for reporting the issue.

I have just deployed the services and I can't reproduce the that error - everything deployed as expected.

I can see `promtail` config present and being mounted.

Could you please provide more information about Kubernetes cluster version, platform etc...

**Comment by bestyuantao** [comment]
Hi @saidsef 

I installed Rancher Desktop in my Windows compute, and my k8s version as below
![image](https://github.com/saidsef/grafana-loki-on-k8s/assets/40762870/c13eeb45-f9a4-4a84-a603-3eb33f94ce48)

and After I commented this line: - -config.file=/etc/promtail/kubernetes-config.yaml, it works, and when I exec to pod, it does has this file, it's wired
![image](https://github.com/saidsef/grafana-loki-on-k8s/assets/40762870/4441a233-9e46-49b3-95a5-37c3cb4c281c)

**Comment by saidsef** [comment]
hmm, 🤔 

@bestyuantao it's strange.  However, I haven't tested it on Rancher Desktop.

I will incorporated your workaround and it should mount the `config.yml` automatically.
